### ISSUE TITLE
Font Setup?

### ISSUE THREAD

**Issue by JBlocklove** [crian/dotfiles#1]
I'm running into a problem with getting your setup for `dwmblocks` to work. I can't seem to get the `siji` font to render properly. How did you set up your fonts, and do you have any fonts installed other than `siji` and `IBM Plex`?

**Comment by crian** [comment]
I'm only using IBM Plex Mono and siji in my current setup. Make sure to set the fonts in dwm config. 
Install siji to `usr/share/fonts` or to `~/.local/share/fonts`.

**Comment by JBlocklove** [comment]
I have siji installed to `~/.local/share/fonts`. I also can't seem to get it to work in my terminal with the `fontalt0` set in `~/.Xresources` like you have. The glyps will show up, though, if it's just `font`, though.

Here's my `~/.Xresources`:
```
st.font: IBM Plex Mono:size=8:antialias=true:autohint=true
st.fontalt0: Wuncon Siji:size=10:antialias=true:autohint=true
st.alpha: 0.65
```
I've had my own `st` install for a while and usually changing things in the `~/.Xresources` works with minimal issue.

The glyphs also still won't show up in `dwm` for me. Here are the fonts from my  `config.h`.
```
static const char *fonts[]           = {
    "IBM Plex Mono:size=10:antialias=true:autohint=true",
	"Wuncon Siji:size=12:antialias=true:autohint=true"
};
```
I've been using `Wuncon Siji` since that's the name I get from running `fc-list`, but I've also tried with just `siji` to no effect.

**Comment by crian** [comment]
Are you using the `siji.ttf` from my dotfiles?

**Comment by JBlocklove** [comment]
No I had installed the font from the siji github. Using your font seems to have fixed it, thanks for your help!

One small related issue, though: for some reason the glyphs only show up as half in my terminal. If I do something like `echo "\ue243"` in my terminal then it won't display the whole glyph. It works fine in the actual dwm bar, though. Any idea why?

**Comment by JBlocklove** [comment]
Well, it appears this problem happens for me with just about any glyph font, so it's definitely unrelated to this issue. Thanks for your help!
